### PR TITLE
Remembering presentation mode state, closes #13

### LINKED ISSUE #13: Remember presentation mode after reboot
Is there a way to make the system stay in presentation mode after reboot? I'm using the latest git be7e0aea with gnome-shell 3.2.1 on Fedora 16.

### PR DESCRIPTION
**Pull request by gaborpapp**
Added modifications to remember the presentation mode state after reboot. Useful for computers that should be in presentation mode permanently.

### CODE REVIEW

**Comment by Mystro256** [comment]
There should be on option to turn this off/on. As well, I would think this option by default this should disabled, though thoroughly noted in the install instructions. It might be interpreted by some as a regression, as many currents users, whom upon updating this extension, may not be used to the behaviour, given that this behaviour is not common feature of inhibiting programs (like caffeine or the old gnome-panel applet).

**Comment by gaborpapp** [comment]
In my opinion this feature is really important in cases where you want to put the computer on display like in exhibitions, museums, etc. And it should run automatically from boot without any user interaction. Adding an option to turn this on and off is not a problem, although then you have to use dconf-editor to change the settings which is not that user-friendly, although many extensions work like this. On the other hand, the behaviour of the accessibility menu is like this, it remembers its settings.

**Comment by Mystro256** [comment]
Well it's up to Raphael; you should add the functionality and maybe add some comments around the line denoting the default value, that way he can change it to his liking. Whether or not he thinks it should be set as default or not, you should still add the function of turning it off for those who dislike it.

**Comment by Mystro256** [comment]
This will not work after I make my merge from my fork, so it will have to be redone after the merge. Sorry ;P

Nice work though!

**Pull request closed without merging**
